version: "3.8"

services:
  translation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi-translation-service
    volumes:
      - ./translations:/app/translations
      - ./translation-cache:/app/translation-cache
    restart: unless-stopped
    command: node fetch-translate.js
    env_file: ./.env
    environment:
      - SOURCE_URL=${SOURCE_URL}
      - SOURCE_TOKEN=${SOURCE_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OUTPUT_DIR=/app/translations
      - CACHE_DIR=/app/translation-cache
      - SOURCE_LOCALE=${SOURCE_LOCALE:-en}
      - TARGET_LANGS=${TARGET_LANGS:-es,fr,de,zh-CN,zh-TW,ja,ru,ar,pl,it,vi,ko}
      - MAX_REPORTS=${MAX_REPORTS:-50}
      - RUN_INTERVAL_MS=${RUN_INTERVAL_MS:-3600000}
    networks:
      - translation-network

  upload-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi-upload-service
    volumes:
      - ./translations:/app/translations
    restart: unless-stopped
    command: node uploadTranslations.js es fr de zh-CN zh-TW ja ru ar pl it vi ko
    env_file: ./.env
    environment:
      - TARGET_URL=${TARGET_URL}
      - TARGET_TOKEN=${TARGET_TOKEN}
      - OUTPUT_DIR=/app/translations
      - UPLOAD_DELAY_MS=${UPLOAD_DELAY_MS:-500}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - RETRY_DELAY_MS=${RETRY_DELAY_MS:-2000}
    depends_on:
      - translation-service
    networks:
      - translation-network

  translation-viewer:
    build:
      context: .
      dockerfile: translation-viewer/Dockerfile
    container_name: translation-viewer
    volumes:
      - ./translations:/app/translations
    environment:
      - PORT=3000
      - TRANSLATIONS_DIR=/app/translations
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - translation-network

networks:
  translation-network:
    driver: bridge
